// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-QOLf_EK1wBds5w28byQ_DruRyuDhJ98',
    appId: '1:640215055360:web:TODO',
    messagingSenderId: '640215055360',
    projectId: 'instagram-e3efe',
    authDomain: 'instagram-e3efe.firebaseapp.com',
    storageBucket: 'instagram-e3efe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-QOLf_EK1wBds5w28byQ_DruRyuDhJ98',
    appId: '1:640215055360:android:6fe18f4eb828833b626ce5',
    messagingSenderId: '640215055360',
    projectId: 'instagram-e3efe',
    storageBucket: 'instagram-e3efe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-QOLf_EK1wBds5w28byQ_DruRyuDhJ98',
    appId: '1:640215055360:ios:TODO',
    messagingSenderId: '640215055360',
    projectId: 'instagram-e3efe',
    storageBucket: 'instagram-e3efe.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-QOLf_EK1wBds5w28byQ_DruRyuDhJ98',
    appId: '1:640215055360:ios:TODO',
    messagingSenderId: '640215055360',
    projectId: 'instagram-e3efe',
    storageBucket: 'instagram-e3efe.appspot.com',
    iosBundleId: 'com.example.instagram',
  );
}
